# Docker
# Build a Docker image 
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- master

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build image
  jobs:  
  - job: Build
    displayName: Build
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: DotNetCoreCLI@2
      inputs:
        command: 'publish'
        publishWebProjects: true
        arguments: '-c Release'
    - task: DotNetCoreCLI@2
      inputs:
        command: 'build'
        arguments: '-c Release'
        workingDirectory: '$(Build.SourcesDirectory)'
    - task: Docker@2
      inputs:
        command: 'build'
        dockerfile: '$(Build.SourcesDirectory)/Dockerfile'
        buildContext: '$(Build.SourcesDirectory)'
        tags: 'sobe'
    - task: Bash@3
      inputs:
        targetType: 'inline'
        workingDirectory: '$(Build.SourcesDirectory)'
        script: |
          echo 'Hello world'
          docker login -u "conseilrqauto" -p "BYXRefe=XifDP2OjCDVxH7ZRYvK5igvP" conseilrqauto.azurecr.io
          docker tag sobe conseilrqauto.azurecr.io/sobe
          docker push conseilrqauto.azurecr.io/sobe
    